// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRLS6214hTj9MiI4in81U8yakE2301B4I',
    appId: '1:876223516259:web:b30cbdbdd6fdfd201eb256',
    messagingSenderId: '876223516259',
    projectId: 'my-instant-g',
    authDomain: 'my-instant-g.firebaseapp.com',
    storageBucket: 'my-instant-g.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB05i9qPh-GgaW3aRkpCd_ukxZiTKrqjE',
    appId: '1:876223516259:android:5119ea38629c66f61eb256',
    messagingSenderId: '876223516259',
    projectId: 'my-instant-g',
    storageBucket: 'my-instant-g.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClkenxWF8fyJsd0PIm9vXIbFRvEnIbgEE',
    appId: '1:876223516259:ios:731e7488a02cc6361eb256',
    messagingSenderId: '876223516259',
    projectId: 'my-instant-g',
    storageBucket: 'my-instant-g.appspot.com',
    iosBundleId: 'com.example.instantgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClkenxWF8fyJsd0PIm9vXIbFRvEnIbgEE',
    appId: '1:876223516259:ios:b2a4f9040045324c1eb256',
    messagingSenderId: '876223516259',
    projectId: 'my-instant-g',
    storageBucket: 'my-instant-g.appspot.com',
    iosBundleId: 'com.example.instantgram.RunnerTests',
  );
}
